region = "ap-northeast-1"
ami = "ami-03f4fa076d2981b45"
itype = "t2.micro"
publicip = true
keyname = "Tokyo"
secgroupname = "Jenkins Ports"
bucketname = "Remote-Statefile"
bucketacl = "private"
ec2name = "Jenkins"