name: Build and Test

on: 
  push: 
    branches: 
      - main

env: 
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs: 
  scripts-unit-tests: 
    name: Scripts Unit Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: .
    steps: 
    - uses: actions/checkout@v3
      name: GitHub Checkout
    - name: Jenkins Install Unit Test
      run: curl -s -O https://raw.githubusercontent.com/RichardDeodutt/Deployment-4/main/Install-Runners/jenkins.sh && sudo chmod +x jenkins.sh && sudo ./jenkins.sh
    - name: Terraform Install Unit Test
      run: curl -s -O https://raw.githubusercontent.com/RichardDeodutt/Deployment-4/main/Install-Runners/terraform.sh && sudo chmod +x terraform.sh && sudo ./terraform.sh
    - name: Agent Install Unit Test
      run: curl -s -O https://raw.githubusercontent.com/RichardDeodutt/Deployment-4/main/Install-Runners/agent.sh && sudo chmod +x agent.sh && sudo ./agent.sh
    - name: Cypress Dependencies Install Unit Test
      run: curl -s -O https://raw.githubusercontent.com/RichardDeodutt/Deployment-4/main/Install-Runners/cydepends.sh && sudo chmod +x cydepends.sh && sudo ./cydepends.sh
    - name: Status Check Unit Test
      run: curl -s -O https://raw.githubusercontent.com/RichardDeodutt/Deployment-4/main/Install-Runners/status.sh && sudo chmod +x status.sh && sudo ./status.sh